apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: redis-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis-deploy
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

